import AppKit

final class ClipboardWatcher {
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private let store: HistoryStore

    init(store: HistoryStore) {
        self.store = store
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer?.invalidate()
        let t = Timer.scheduledTimer(withTimeInterval: 0.2, repeats: true) { [weak self] _ in
            self?.tick()
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func tick() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        guard store.captureEnabled else { return }

        let types = pasteboard.types ?? []
        let sensitiveHints: Set<String> = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword"
        ]
        if types.contains(where: { sensitiveHints.contains($0.rawValue) }) {
            return
        }

        let frontApp = NSWorkspace.shared.frontmostApplication
        if let bundleID = frontApp?.bundleIdentifier,
           Settings.shared.excludedBundleIDs.contains(bundleID) {
            return
        }

        guard let text = pasteboard.string(forType: .string), !text.isEmpty else { return }

        if Settings.shared.blockLikelySecrets && SecretHeuristic.looksLikeSecret(text) {
            return
        }
        store.add(text: text,
                  sourceBundle: frontApp?.bundleIdentifier,
                  sourceName: frontApp?.localizedName)
    }
}
